### ISSUE TITLE
Support for groups

### ISSUE THREAD

**Issue by reinzor** [pal-robotics/ddynamic_reconfigure#11]
Dynamic reconfigure has support for group. Ddynamic reconfigure has not. Open to accept a PR for this? What are your thoughts?

**Comment by reinzor** [comment]
Closed since #12 is merged

**Comment by Timple** [comment]
Am I correct that this feature is not available in [ddynamic_reconfigure_python](https://github.com/pal-robotics/ddynamic_reconfigure_python)?

**Comment by reinzor** [comment]
That is correct AFAIK

**Comment by Timple** [comment]
Alrighty, if my need becomes large enough I'll see if I can pick it up :slightly_smiling_face:
