### ISSUE TITLE
Using ddynamic_reconfigure as a client

### ISSUE THREAD

**Issue by msadowski** [pal-robotics/ddynamic_reconfigure#13]
Hi!

Many thanks for making this package! I find it very useful!

I've looked through the readme and scrolled to the code and it seems to me that currently it's not possible to use ddynamic_reconfigure as a client to a dynamic reconfigure started by another node. Can someone confirm this is a case?

**Comment by v-lopez** [comment]
I am not sure I understand your use case, `ddynamic_reconfigure` is an alternative to a `dynamic_reconfigure` server, but the client is the same for both.

**Comment by msadowski** [comment]
That makes sense, thanks!
