### ISSUE TITLE
Is there a difference between registerVariable and RegisterVariable?

### ISSUE THREAD

**Issue by vkotaru** [pal-robotics/ddynamic_reconfigure#16]
Hi, 

Thank you for the ddynamic_reconfigure. 

I have noticed there are two different implementations to register variables. registerVariable as described in the README.md and RegisterVariable as shown in [line 65, test_ddynamic_reconfigure.cpp](https://github.com/pal-robotics/ddynamic_reconfigure/blob/83706e1b3f2a157c331e4bb16cb1ad0d2df36799/test/test_ddynamic_reconfigure.cpp#L65). Is there any implementation difference between these two? 

Thank you

**Comment by v-lopez** [comment]
Like the header says [here](https://github.com/pal-robotics/ddynamic_reconfigure/blob/kinetic-devel/include/ddynamic_reconfigure/ddynamic_reconfigure.h#L114) they are deprecated, do not use them.
