### ISSUE TITLE
support for `float` type

### ISSUE THREAD

**Issue by naveedhd** [pal-robotics/ddynamic_reconfigure#2]
Hi,

I have a use case where a 3rd party library has float inputs, that I want to reconfigure in my code.

right now I am resorting to `double` and implicit conversions but would it be good to have instantiations for `float` also?

**Comment by v-lopez** [comment]
The dynamic_reconfigure API which this is based on (from ROS) only supports int, bool, double, string and enums: http://docs.ros.org/melodic/api/dynamic_reconfigure/html/index-msg.html

Internally we'd end up converting the float to double anyway, so I believe it would be confusing to support it externally but convert it internally.

**Comment by naveedhd** [comment]
ah makes sense! thanks!
