### ISSUE TITLE
Bug: 'atomic_bool' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by YuhsiHu** [pal-robotics/ddynamic_reconfigure#21]
Hi, some errors happened when we compiled the version after you merge in 2020.01.  We have rolled back the version and it can run normally.
![微信图片_20210118155851](https://user-images.githubusercontent.com/34529345/104887345-14013a00-59a6-11eb-9f98-0e92ac1f0315.jpg)

**Comment by v-lopez** [comment]
You need to build with C++11 flags to have access to atomic_bool.

**Comment by YuhsiHu** [comment]
At the beginning I updated the versions of gcc and g++. Now I realized that simply updating the version does not make std support c++11 when compiling. Maybe I can write it in cmakelists？

**Comment by v-lopez** [comment]
Please check if the latest version that we have pushed solves your issues.

**Comment by YuhsiHu** [comment]
Yes, the latest version can be compiled normally, thank you very much!
