### ISSUE TITLE
Specifying node handle for ddr

### ISSUE THREAD

**Issue by Patrick-Lascombe** [pal-robotics/ddynamic_reconfigure#5]
First thanks for this tool that simplifies dynamic_reconfigure. But I have one small problem. I cannot specify the node handle for a specific ddr. 
In the first picture there is rqt working with the classic dynamic_reconfigure and there is inside the nodelet r2000_nodelet_manager, 2 dynamic reconfigure implementation : AngularBoundsFilter and IntensityFilter.

![dr](https://user-images.githubusercontent.com/44769524/59666183-a3d07800-91b4-11e9-9295-19d85d788d75.png)

In this image I replaced the dr of the intensity filter with the ddr, and ddr is linked with the nodelet manager
![ddr](https://user-images.githubusercontent.com/44769524/59666182-a337e180-91b4-11e9-9f39-b2b261f6dd5c.png)

How can I do to specify the node handle and have the same result as in the first picture ?

Here is my instantiation of the ddr :

```
public:

  double lower_threshold_ ;
  double upper_threshold_ ;
  int disp_hist_ ;
  bool disp_hist_enabled_;
  ddynamic_reconfigure::DDynamicReconfigure ddr;

  bool configure()
  {
    ros::NodeHandle nh_("~/IntensityFilter");

    lower_threshold_ = 8000.0;
    upper_threshold_ = 100000.0;
    disp_hist_ = 1;

    getParam("lower_threshold", lower_threshold_);
    getParam("upper_threshold", upper_threshold_) ;
    getParam("disp_histogram",  disp_hist_) ;


    ddr.registerVariable<double>("Lower_intensity", &lower_threshold_, "Lower intensity threshold", 0, 3000);
    ddr.registerVariable<double>("Upper_intensity", &upper_threshold_, "Upper intensity threshold", 0, 3000);
    ddr.publishServicesTopics();

    disp_hist_enabled_ = (disp_hist_ == 0) ? false : true;

    return true;
  }
```

Thanks for your help

**Comment by lucasw** [comment]
It's in the constructor `DDynamicReconfigure(const ros::NodeHandle &nh)` https://github.com/pal-robotics/ddynamic_reconfigure/blob/kinetic-devel/src/ddynamic_reconfigure.cpp#L5

If your node handle isn't yet available for the ddr object you can do something like:

```
std::unique_ptr<ddynamic_reconfigure::DDynamicReconfigure> ddr;
...  // create a node handle
ddr = std::make_unique<ddynamic_reconfigure::DDynamicReconfigure>(nh);
ddr->registerVariable...
```

(using `-std=c++14`)

**Comment by facontidavide** [comment]
I think the examples in the README.md should make use of the NodeHandle.

**Comment by v-lopez** [comment]
Agreed, I have added them.
