### ISSUE TITLE
CMake Error: "Cannot specify link libraries for target "ddynamic_reconfigure-test""

### ISSUE THREAD

**Issue by matthiashh** [pal-robotics/ddynamic_reconfigure#6]
Similar to #4, I couldn't build this repo right away, but this time under `melodic` getting this error:
```
CMake Error at /home/matthias/Workspaces/rss_ws/src/libs/ddynamic_reconfigure/CMakeLists.txt:57 (target_link_libraries):
  Cannot specify link libraries for target "ddynamic_reconfigure-test" which is not built by this project
```

It that's this in the `CMakeLists`:
```
if (CATKIN_ENABLE_TESTING)
    find_package(rostest REQUIRED)
    add_rostest_gmock(ddynamic_reconfigure-test test/ddynamic_reconfigure.test test/test_ddynamic_reconfigure.cpp)
    target_link_libraries(ddynamic_reconfigure-test
                                ${PROJECT_NAME})
```

It doesn't look all that wrong following some information about `add_rostest_gmock` and obviously it compiles using `catkin build --cmake-args -DCATKIN_ENABLE_TESTING=False`, but that's only a workaround.

Does somebody know how the proper solution would look like?

**Comment by v-lopez** [comment]
Could you provide the CMake output? Probably it's not being able to create the executable due to some issue with gmock.

**Comment by matthiashh** [comment]
```
matthias@matthias-laptop:~/Workspaces/ddynamic_reconfigure_ws$ catkin b
==> Expanding alias 'b' from 'catkin b' to 'catkin build'
--------------------------------------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/melodic
Workspace:                   /home/matthias/Workspaces/ddynamic_reconfigure_ws
--------------------------------------------------------------------------------------
Build Space:        [exists] /home/matthias/Workspaces/ddynamic_reconfigure_ws/build
Devel Space:        [exists] /home/matthias/Workspaces/ddynamic_reconfigure_ws/devel
Install Space:      [unused] /home/matthias/Workspaces/ddynamic_reconfigure_ws/install
Log Space:          [exists] /home/matthias/Workspaces/ddynamic_reconfigure_ws/logs
Source Space:       [exists] /home/matthias/Workspaces/ddynamic_reconfigure_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                                                                                                   
[build] Updating package table.                                                                                                                                              
Starting  >>> ddynamic_reconfigure                                                                                                                                           
_____________________________________________________________________________________________________________________________________________________________________________
Errors     << ddynamic_reconfigure:cmake /home/matthias/Workspaces/ddynamic_reconfigure_ws/logs/ddynamic_reconfigure/build.cmake.000.log                                     
CMake Error at /home/matthias/Workspaces/ddynamic_reconfigure_ws/src/ddynamic_reconfigure/CMakeLists.txt:57 (target_link_libraries):
  Cannot specify link libraries for target "ddynamic_reconfigure-test" which
  is not built by this project.


cd /home/matthias/Workspaces/ddynamic_reconfigure_ws/build/ddynamic_reconfigure; catkin build --get-env ddynamic_reconfigure | catkin env -si  /usr/bin/cmake /home/matthias/Workspaces/ddynamic_reconfigure_ws/src/ddynamic_reconfigure --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/matthias/Workspaces/ddynamic_reconfigure_ws/devel/.private/ddynamic_reconfigure -DCMAKE_INSTALL_PREFIX=/home/matthias/Workspaces/ddynamic_reconfigure_ws/install; cd -
.............................................................................................................................................................................
Failed     << ddynamic_reconfigure:cmake          [ Exited with code 1 ]                                                                                                     
Failed    <<< ddynamic_reconfigure                [ 2.3 seconds ]                                                                                                            
[build] Summary: 0 of 1 packages succeeded.                                                                                                                                  
[build]   Ignored:   None.                                                                                                                                                   
[build]   Warnings:  None.                                                                                                                                                   
[build]   Abandoned: None.                                                                                                                                                   
[build]   Failed:    1 packages failed.                                                                                                                                      
[build] Runtime: 2.4 seconds total.                                                                                                                                          
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

**Comment by v-lopez** [comment]
Please clean the workspace and run it again, otherwise cmake is not re-executed and we cannot see the meaningful output.

**Comment by matthiashh** [comment]
This is the output of a brand new workspace that I 
1. built being empty
2. cloned `ddynamic_reconfigure`
3. built again (output supplied)

If I run `catkin clean -y` and `catkin build` again I get the same output. The log is to be found [here](https://pastebin.com/KsYWzFw4).

**Comment by v-lopez** [comment]
Ok, please build it with `-v` to get some more output.

**Comment by matthiashh** [comment]
* [Console output](https://pastebin.com/w8yHfujA)
* [CMakeOutput.log](https://pastebin.com/pb38et9v)
* [CMakeError.log](https://pastebin.com/FHZPRLQD)

Looks like it couldn't find `pthread`. Looking at installed packages I find only `libpthread-stubs0-dev` being installed on my system.

I executed `rosdep install --from-paths src --ignore-src --rosdistro=melodic -y` before though - shouldn't that take care of all the dependencies?

**Comment by v-lopez** [comment]
I've got the same output regarding to pthread.

Can you try to find your gmock installation?
In my case:
```
$ dpkg -S gmock.h
googletest:amd64: /usr/src/googletest/googlemock/include/gmock/gmock.h
googletest:amd64: /usr/include/gmock/gmock.h

$ dpkg -S gtest.h
googletest:amd64: /usr/include/gtest/internal/custom/gtest.h
googletest:amd64: /usr/include/gtest/gtest.h
googletest:amd64: /usr/src/googletest/googletest/include/gtest/internal/custom/gtest.h
googletest:amd64: /usr/src/googletest/googletest/include/gtest/gtest.h
```

And my googletest version is 1.8.0-6

**Comment by matthiashh** [comment]
gmock installation: 
```
matthias@matthias-laptop:~$ dpkg -S gmock.h
googletest:amd64: /usr/src/googletest/googlemock/include/gmock/gmock.h
googletest:amd64: /usr/include/gmock/gmock.h
matthias@matthias-laptop:~$ dpkg -S gtest.h
googletest:amd64: /usr/include/gtest/internal/custom/gtest.h
googletest:amd64: /usr/include/gtest/gtest.h
googletest:amd64: /usr/src/googletest/googletest/include/gtest/internal/custom/gtest.h
googletest:amd64: /usr/src/googletest/googletest/include/gtest/gtest.h
```

googletest version:
```
matthias@matthias-laptop:~$ dpkg --status libgtest-dev 
Package: libgtest-dev
Status: install ok installed
Priority: extra
Section: oldlibs
Installed-Size: 17
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: googletest
Version: 1.8.0-6
```

**Comment by v-lopez** [comment]
That's weird.

I'm insisting so much on gmock, because I've seen this behavior before. If gmock is not found, the target is not added (see [this](https://github.com/ros/catkin/blob/kinetic-devel/cmake/test/gtest.cmake#L151)) and the target_link_libraries fails.

You could try to add some debug statements in `/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake` to see if this is the case.

**Comment by matthiashh** [comment]
It builds on my other 18.04 machine, so it seems to be something in the configuration of my laptop which I couldn't find up to now. Even reinstalling ROS and setting up the workspace didn't work.

Here's the output of `/home/matthias/Workspaces/ddynamic_reconfigure_ws/logs/ddynamic_reconfigure/build.cmake.000.log` for the two machines.
- [not working](https://pastebin.com/MDte3XpZ)
- [working](https://pastebin.com/zrHyruPH)

But it doesn't look like it's something specific to `ddynamic_reconfigure`, but more a `catkin` configuration issue. 

---------

The crucial difference for me seems to be the order in which it runs through packages on the laptop vs the workstation. 

Also the `CMAKE_PREFIX_PATH` looks wrong on the laptop, but the happens even with `catkin clean` and `catkin config` or `catkin_tools/profiles/default/config.yaml` are the same on both machines.

**Comment by v-lopez** [comment]
It looks like in your **working** version gmock is found
`^[[36m--^[[0m Found gmock sources under '/usr/src/googletest': gmock will be built`
and in the **not working**

`[36m--[0m Found gtest: gtests will be built`

Only gtest is found.

**Comment by matthiashh** [comment]
I screwed up to name the links -.- I renamed them now by editing the original post.

**Comment by v-lopez** [comment]
I don't understand your last message, which links?

**Comment by matthiashh** [comment]
In  https://github.com/pal-robotics/ddynamic_reconfigure/issues/6#issuecomment-532219927 I mixed up the pastebin links and the naming of the links. The link with the name "working" was linking to the "not working" output on pastebin. So I fixed the naming of the links by editing the comment.

In the mean time I played around with `/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake`.
Turns out that both the statements `if(NOT GMOCK_FOUND)` and `if(NOT GTEST_FOUND)` around line 290 are satisfied on the machine that can build it.

**Comment by matthiashh** [comment]
I also compared all packages installed on both machines and I didn't find find any differences for any `gmock`, `gtest` packages or so.

**Comment by matthiashh** [comment]
Well, after a bit of more digging it turned out that `/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake` would search for `gmock`, doesn't find it and searches for `gtest`. If there's still no success there seems to be some manual stuff. Here it becomes interesting:

- On the workstation it doesn't find `GTEST_LIBRARY GTEST_MAIN_LIBRARY` and goes into a `else` in the ROS `gtest.cmake` where this seems to be done manually - **that works**
- On my laptop it finds `gtest` since there's at least `/usr/lib/libgtest.a` (which dpkg doesn't know about and neither do I) and then it fails later on.

Well, anyhow. It's not connected to `ddynamic_reconfigure`, so I will close this. I settled upon moving `/usr/lib/libgtest.a` since I don't know where it comes from anyway and now it builds on my laptop as well. Thanks for the help.

**Comment by v-lopez** [comment]
Wow that was a tricky one. Good job finding it.
