### ISSUE TITLE
getMax()... is min !

### ISSUE THREAD

**Issue by facontidavide** [pal-robotics/ddynamic_reconfigure#8]
https://github.com/pal-robotics/ddynamic_reconfigure/blob/kinetic-devel/include/ddynamic_reconfigure/ddynamic_reconfigure_utils.h#L57

**Comment by v-lopez** [comment]
Fixed in https://github.com/pal-robotics/ddynamic_reconfigure/commit/e2ee48780f8a4456151c4bca9f8ba4af94311938

Thanks for spotting it
